# -*- coding: utf-8 -*-
"""ejercicios clase 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LcO7D6mI5_9aZEW9SaeQCnLLLZWvnrId
"""

A = int(input("Ingrese un valor: "))
B = int(input("ingrese el segundo valor: "))
if A<=B:
  print("A es menor o igual que B")
else:
  print("A es mayor que B")

A = float(input("Nota 1: "))
B = float(input("Nota 2: "))
C = float(input("Nota 3: "))
D = float(input("Nota 4: "))
E = float(input("Nota 5: "))
F = float(A*0.3+B*0.15+C*0.15+D*0.2+E*0.2)
if A<0 or A>5 or B<0 or B>5 or C<0 or C>5 or D<0 or D>0 or D>5 or E<0 or E>5:
  print("error")
else:
  print(F)
if F>=3:
  print("ganó")
else:
  print("perdió")

A = float(input("Nota 1: "))
B = float(input("Nota 2: "))
C = float(input("Nota 3: "))
D = float(input("Nota 4: "))
E = float(input("Nota 5: "))
F = float(A*0.3+B*0.15+C*0.15+D*0.2+E*0.2)

if F>=3:
  print("ganó")
else:
  print("perdió")